# Generated by Django 5.0.3 on 2024-03-19 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('Model1', 'Model 1'), ('Model2', 'Model 2'), ('Model3', 'Model 3')], max_length=20)),
                ('details', models.TextField()),
                ('maitre_ouvrage', models.CharField(max_length=100)),
                ('marche', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
