# Generated by Django 5.0.3 on 2024-03-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='constructeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=30, verbose_name='Lib :')),
            ],
            options={
                'verbose_name': 'Contractant',
                'verbose_name_plural': 'Contractants',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_attache', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date arrivé')),
                ('titre', models.CharField(max_length=20, verbose_name='Objet')),
                ('doc', models.FileField(blank=True, null=True, upload_to='MyUpload/projets', verbose_name='Fichier')),
                ('rapport', models.TextField(verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='etat_emploiye',
            fields=[
                ('id_etat', models.AutoField(primary_key=True, serialize=False)),
                ('lib_etat', models.CharField(max_length=30, verbose_name='Etat employé:')),
            ],
            options={
                'verbose_name': 'Etat employé',
                'verbose_name_plural': 'Etat employé',
            },
        ),
        migrations.CreateModel(
            name='etat_projet',
            fields=[
                ('id_etat', models.AutoField(primary_key=True, serialize=False)),
                ('lib_etat', models.CharField(max_length=30, verbose_name='Etat projet:')),
            ],
            options={
                'verbose_name': 'Etat projet',
                'verbose_name_plural': 'Etat projet',
            },
        ),
        migrations.CreateModel(
            name='marche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=30, verbose_name='Num Marché:')),
                ('details', models.TextField(verbose_name='Details:')),
            ],
        ),
        migrations.CreateModel(
            name='mouvrage',
            fields=[
                ('id_mo', models.AutoField(primary_key=True, serialize=False)),
                ('lib_mo', models.CharField(max_length=30, verbose_name='Maitre ouvrage:')),
                ('details', models.TextField(verbose_name='Details:')),
            ],
            options={
                'verbose_name': 'Maitre ouvrage',
                'verbose_name_plural': 'Maitre ouvrages',
            },
        ),
        migrations.CreateModel(
            name='procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=1, verbose_name='Titre')),
                ('detail', models.TextField(verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedure',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id_Ress', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Matériel de Transport'), ('2', 'Matériel pour le Diagnostic'), ('3', 'Matériel pour le Mesure'), ('4', 'Matériel de Nettoyage'), ('5', 'Matériel pour gros oeuvre'), ('6', 'Matériel pour second oeuvre'), ('7', 'Matériel pour Espace verts'), ('8', 'Matériel pour Industrie'), ('9', 'Matériel de Manutention'), ('10', 'Matériel de Signalisation'), ('11', 'Matériel portatif'), ('12', 'Engins de Terrasement'), ('13', 'Machines à Projete'), ('14', 'Electricité sur chantiers'), ('15', 'Autre')], max_length=2, verbose_name='TYPE')),
                ('lib', models.CharField(max_length=25, verbose_name='Nom')),
                ('nom', models.CharField(max_length=25, verbose_name='MARQUE / MODEL')),
                ('code', models.CharField(max_length=25, verbose_name='CODE BARRES / MATRICUL')),
                ('dispo', models.CharField(choices=[('1', 'Disponible'), ('2', 'En Panne'), ('3', 'Louer')], max_length=1, verbose_name='DISPONIBILITE')),
                ('etat', models.CharField(choices=[('1', 'Bonne Etat '), ('2', 'Endomagé'), ('3', 'En Panne')], max_length=1, verbose_name='ETAT')),
            ],
        ),
        migrations.CreateModel(
            name='specialite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=30, verbose_name='Nom :')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialité',
            },
        ),
        migrations.CreateModel(
            name='Type_doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=50, verbose_name='lib')),
            ],
            options={
                'verbose_name': 'Table Gestion des doc',
                'verbose_name_plural': 'Table Gestion des doc',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('Id_agent', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_agent', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nom employé')),
                ('Poste', models.CharField(blank=True, choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('7', 'Chef Stucture'), ('8', 'Admin Projets'), ('9', 'Ingénieur D Etudes'), ('10', 'Chargé D Etudes '), ('11', 'Exploitant '), ('12', 'Exécutant '), ('13', 'Chef Projet'), ('14', 'Chef Partie')], max_length=3, null=True, verbose_name='Titre')),
                ('Mat_agent', models.CharField(blank=True, max_length=10, null=True, verbose_name='MAT')),
                ('Bureau', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bureau')),
                ('tel', models.CharField(max_length=25, verbose_name='Tel')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('lib_dir', models.CharField(max_length=30, verbose_name='Lib')),
                ('reponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.agent', verbose_name='Responsable')),
                ('structure_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.direction', verbose_name='Structure parente')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='Direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.direction', verbose_name='Structure'),
        ),
        migrations.CreateModel(
            name='date_document',
            fields=[
                ('id_po', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lib', models.CharField(max_length=40)),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.document')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='etatag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.etat_emploiye', verbose_name='Etat employé'),
        ),
        migrations.CreateModel(
            name='pointage',
            fields=[
                ('id_po', models.AutoField(primary_key=True, serialize=False)),
                ('date_po', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('Lib', models.CharField(max_length=50, verbose_name='PROJET')),
                ('details', models.TextField(verbose_name='DETAILS')),
                ('date_deb', models.DateField(blank=True, null=True, verbose_name='DATE Debut Contractuele')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='DATE Mise en vigueur')),
                ('chart', models.BooleanField(default=True, verbose_name='Afficher sur Dashbord')),
                ('archiv', models.BooleanField(default=True, verbose_name='ARCHIVE')),
                ('maquette', models.BooleanField(verbose_name="C'est un projet modele")),
                ('Chef_PROJET', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agent', verbose_name='CHEF PROJET')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.etat_projet', verbose_name='ETAT DU PROJET')),
                ('ismaquette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetteProjet', to='login.projet', verbose_name='Modele')),
                ('maitreouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.mouvrage', verbose_name='MAITRE OUVRAGE')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id_al', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50, verbose_name='Titre')),
                ('type', models.CharField(choices=[('1', 'information '), ('2', 'Avertissement'), ('3', 'Probleme')], max_length=1, verbose_name='Type')),
                ('date_al', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('details', models.TextField(verbose_name='Details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.projet')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.projet'),
        ),
        migrations.CreateModel(
            name='sig_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.document')),
                ('signatair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.agent', verbose_name='signatair')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='specia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.specialite', verbose_name='Specialite'),
        ),
        migrations.CreateModel(
            name='suivi_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('detail', models.TextField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.agent')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('Lib', models.CharField(max_length=50, verbose_name='Titre')),
                ('delais', models.IntegerField(blank=True, null=True, verbose_name='Durée (Semaine)')),
                ('date_deb_tot', models.DateField(blank=True, null=True, verbose_name='Date Debut au plus tot')),
                ('date_deb_tard', models.DateField(blank=True, null=True, verbose_name='Date Debut au plus tard')),
                ('date_deb', models.DateField(blank=True, null=True, verbose_name='Date Debut réel')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date Fin')),
                ('pourcentage', models.FloatField(default=0, verbose_name='Pourcentage du projet (%)')),
                ('progress', models.FloatField(default=0, verbose_name='PROGRESSION (%) ')),
                ('Listtache', models.TextField(blank=True, null=True)),
                ('Chef_PROJET', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agent', verbose_name='Responsable')),
                ('Tache_presedent', models.ManyToManyField(blank=True, null=True, to='login.tache')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tacheper', to='login.tache', verbose_name='Partie Reference')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='Tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.tache'),
        ),
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('detail', models.TextField()),
                ('agent_decl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.agent', verbose_name='Agent Déclencheur')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.projet')),
                ('Tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.tache')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='Tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.tache', verbose_name='Partie'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField(verbose_name='detail ')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='DATE/Heure')),
                ('type', models.CharField(blank=True, choices=[('1', 'CE'), ('2', 'CPREG')], default='1', max_length=5, verbose_name='Type')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.projet', verbose_name='Projet')),
                ('partie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.tache', verbose_name='Partie Projet')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commission',
            },
        ),
        migrations.CreateModel(
            name='tache_Agent',
            fields=[
                ('id_pa', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(blank=True, choices=[('1', 'President Directeur Générale'), ('2', 'Directeur Générale'), ('3', 'Assistant'), ('4', 'Consultant'), ('7', 'Chef Stucture'), ('8', 'Admin Projets'), ('9', 'Ingénieur D Etudes'), ('10', 'Chargé D Etudes '), ('11', 'Exploitant '), ('12', 'Exécutant '), ('13', 'Chef Projet'), ('14', 'Chef Partie')], max_length=2, null=True, verbose_name='Role')),
                ('date_deb', models.DateField(blank=True, null=True, verbose_name='Date Debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date Fin')),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.agent')),
                ('Projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.projet', verbose_name='Tache/Projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.tache', verbose_name='Tache/Projet')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
            },
        ),
        migrations.CreateModel(
            name='tache_Ressource',
            fields=[
                ('id_pr', models.AutoField(primary_key=True, serialize=False)),
                ('date_deb', models.DateField(blank=True, null=True, verbose_name='Date Debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date Fin')),
                ('Projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tache')),
                ('Ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='traitement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('Echiance', models.DateTimeField(blank=True, null=True, verbose_name='Echiance')),
                ('detail', models.TextField()),
                ('doc', models.FileField(blank=True, null=True, upload_to='MyUpload/traitement', verbose_name='Pice joint')),
                ('etat', models.CharField(choices=[('1', 'En Cour'), ('2', 'Cloturé'), ('3', 'Probleme'), ('4', 'Annulé')], max_length=1, verbose_name='ETAT')),
                ('Tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.tache')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_demandeur', to='login.agent', verbose_name='Demandeur')),
                ('executant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.agent', verbose_name='executant')),
                ('procedu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.procedure', verbose_name='procedure')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.projet')),
            ],
            options={
                'verbose_name': 'Travail',
                'verbose_name_plural': 'Travaux',
            },
        ),
        migrations.CreateModel(
            name='suiv_traitement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('detail', models.TextField()),
                ('doc', models.FileField(blank=True, null=True, upload_to='MyUpload/traitement', verbose_name='Pice joint')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agent', verbose_name='Auteur')),
                ('traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.traitement', verbose_name='procedure')),
            ],
            options={
                'verbose_name': 'Reponse Travail',
                'verbose_name_plural': 'Reponse Travaux',
            },
        ),
        migrations.CreateModel(
            name='act_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.document')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.traitement', verbose_name='traitement a faire')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.type_doc'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
