# Generated by Django 5.0.3 on 2024-03-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_utilisateur_statu_equipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
